local base_colors = {
  black = "#616161",
  blue = "#afd4fa",
  cyan = "#d0d1fa",
  green = "#c3f884",
  magenta = "#f295f7",
  red = "#f08978",
  light_white = "#ffffff",
  white = "#f1f1f1",
  yellow = "#fefdc8",
  background_light = "#2a2929",
  background = "#1e2021",
  background_dark = "#201f1f",
  foreground = "#c7c7c7",
  selection = "#29302b",
  brown = "#453326",
  -- auxilliery colors --> remove
  grey = "#a1aab4",
  line = "#504f4f",
  dark_green = "#003748",
  orange = "#f34b00",
  dark_blue = "#178ec8",
  dark_purple = "#c678dd",
  pink = "#d3859b",
}
local M = {
  -- Base Colors
  black = base_colors.black,
  background = base_colors.background,
  background_dark = base_colors.background_dark,
  background_light = base_colors.background_light,
  selection = base_colors.selection,
  blue = base_colors.blue,
  cyan = base_colors.cyan,
  green = base_colors.green,
  purple = base_colors.magenta,
  red = base_colors.red,
  light_white = base_colors.light_white,
  white = base_colors.white,
  grey = base_colors.grey,
  line = base_colors.line,
  dark_green = base_colors.dark_green,
  orange = base_colors.orange,
  dark_blue = base_colors.dark_blue,
  dark_purple = base_colors.dark_purple,
  yellow = base_colors.yellow,
  pink = base_colors.pink,
  pmenu_bg = base_colors.background_light,

  -- text
  text_primary = base_colors.white,
  text_highlight = base_colors.yellow,
  line_nr = base_colors.line,
  -- Component specific colors
  pmenu_sel_bg = base_colors.selection,
  statusline_bg = base_colors.background_light,
  folder_bg = "#86a5ff",
  cursor_line_background = base_colors.background_light,
  cursor_line_frontground = base_colors.line,
  git_signs_add = "#487e02",
  git_signs_blame = base_colors.line,
  cmp_background = base_colors.background_light,
  telescope_background = base_colors.background_light,
  noice_background = base_colors.background_light,
  -- Lualine
  lualine_background = base_colors.background,
  lualine_background_dark = "#2a75a6",
  lualine_mode_background = base_colors.background_dark,
  lualine_normal_foreground = base_colors.red,
  lualine_insert_foreground = base_colors.green,
  lualine_lsp_foreground = base_colors.blue,
  lualine_progress_foreground = base_colors.red,
  lualine_location_foreground = base_colors.red,
  lualine_filetype_foreground = base_colors.blue,
  lualine_diff_add = base_colors.green,
  lualine_diff_change = base_colors.yellow,
  lualine_diff_delete = base_colors.red,
  lualine_branch = base_colors.magenta,
  -- Barbar
  barbar_background = base_colors.background,
  barbar_background_inactive = base_colors.background_light,
  barbar_background_current = base_colors.background,
  barbar_current_index = base_colors.background,
  barbar_inactive_index = base_colors.background_light,
  which_key_background = base_colors.background_dark,
  diagnostics_error = "#f14c4c",
  diagnostic_unnecessary = '#a79d82',
  ibl_line = "#2f302e",
  ibl_scope = base_colors.red,
  scrollview = "#3b3937",

  -- Neo Tree
  neo_tree_background = base_colors.background,
  neo_tree_modified = "#e2a974",
  neo_tree_root_background = "#1a304d",
  neo_tree_winbar_background = "#1a304d",
  -- CMP
  cmp_text = base_colors.grey,
  winbar_background = base_colors.background,
  keyword = "#fe8018",
  keyword_import_typescript = "#fb4834",
  keyword_coroutine_typescript = "#fb4834",
  type = "#fabd2f",
  variable = "#83a598",
  variable_member = "#83a598",
  property = "#83a598",
  string = "#b8bb26",
  func = "#8ec07c",
  operator = "#fe8019",
  bracket = "#b16286",
  special = base_colors.pink,
  delimiter = "#8ec07c",
  match_paren_background = "#5e564e",
  variable_builtin = base_colors.pink,
  constant = base_colors.pink,
  comment = "#8f8476",
  copilot_completion = "#737272",
  --
  barbar_current = "#8ec07c",
  search = "#393527"
}

return M
